language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-7.0

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git -b v7.4.1 # Clone pillar before it was dev-7 and worked
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-TestingInPharo
  skip_cleanup: true
  user: ducasse
  key:
    secure: FiFVkmdip7Xpe1SS0yDSkXnYOe0IsuH8FA8zuvlZo1Xmb04FPdF5shV8i2nP+ZLTvzwSNPELZFa76z4pEz7M8hOXg6J+OGZ4dyvaIQpCSP2kvCQSqXkk3iq3xy3ZmE2VQLGf0ZLFh8gJ//LtiHQALQYhQab3KgdyRO20p+/+Ntl/W0DF++Cv6+VpkJl5yV2WRS2ySZHkMzYTvHBthGXBkULP3gb2tCvNx/RFbDKkoH7+I2v0w0//F/NYQGkprW/h0ktXFy/49oiqKQEEZmHUKvE7yFkaRPn5qEbwdS+VN7bVPmkH8BEtHlzBAADF/uPXXHKdHBrHEcdsE7wJ1EMR/iAoEukdndfj7cjh971Om6Bfhw8l7o1tCzn1QVXmskswWc29W+odDs2yhGW5aBhAK3ZHtqP0mQCsHYcMBppdcjzOL9uDPYUTMcx19CKosRIyEkZ7NF+FTftmfroZ2mmpboqdIId8uiP4Zu75u9qEwycCF3zrjoeBh7MmQAEByRsi6cZ5dNEG/6xVjg1kxnxHw59FdS8kwYBTA6JtRY55d/7VodM316OexkOzs05Oz9TjAh9AZ3kMvYWs6sijUPQrm49zFhoBSNNOezoFHAoe8ivIiNiIq519QW6b3kLDuoXzPCPsvuqKtQ1S86afB9tPaV1XR3wvJK+otGTxyF9cPgQ=